## TODO: context_bootstrap is referenced with a hardcoded name in a
## few places and should not be.

setup_bootstrap <- function(root) {
  path <- path_version(root)
  written <- read_version(root)
  installed <- packageVersion("context")
  if (is.na(installed) || written < installed) {
    write_bootstrap(root)
    write_runner(root)
    invisible(TRUE)
  } else if (written > installed) {
    ## This might get relaxed.
    stop("context version conflict; local is outdated")
  } else {
    invisible(FALSE)
  }
}

read_version <- function(root) {
  filename <- path_version(root)
  if (file.exists(filename)) {
    package_version(readLines(filename))
  } else {
    package_version("0.0")
  }
}

## This attempts to write out enough of the package to bootstrap the
## package into working.  It uses the actual package functions rather
## than anything else so that's nice.
##
## One issue is that libcurl is going to be required to satisfy the
## curl dependency.  That's not very pleasant to deal with.  In the
## docker case we could attempt to fix that with an
##   apt-get update && apt-get -y libcurl4-openssl-dev
## but that seems to be asking a little too much.
##
##   platform <- function() {
##     name <- tolower(Sys.info()[["sysname"]])
##     if (name == "linux") {
##       tmp <- strsplit(readLines("/proc/self/cgroup") ":", fixed=TRUE)
##       if (any(grepl("docker", vapply(tmp, "[[", character(1), 3L)))) {
##         name <- "docker"
##       }
##     }
##     name
##   }
##
## But for now, I'll just require it.
##
## It would probably be better to stick the files into a drat and
## install off that; that removes any separate package installation
## (github urls etc).  and we could actually install it into a
## separate local library.  Only downside is that during development
## it's then difficult to get the most recent version.
write_bootstrap <- function(root) {
  bootstrap <- function(root, version) {
    options(context.log=TRUE)
    oo <- options(repos=c(CRAN="http://cran.rstudio.com"))
    on.exit(options(oo))
    context_log("bootstrap", normalizePath(root))
    use_local_library(path_library(root))
    if ("context" %in% .packages(TRUE)) {
      if (isTRUE(packageVersion("context") >= read_version(root))) {
        context_log("ok", "")
        return()
      }
    }
    deps <- c("curl", "drat")
    packages <- setdiff(deps, .packages(TRUE))
    if (length(packages) > 0L) {
      context_log("install", paste(packages, collapse=", "))
      install.packages2(packages)
    }
    url <- github_url("dide-tools", "context", "master")
    filename <- download_file(url, tempfile("context_"))
    path <- tempfile("path")
    unzip(filename, exdir=path)
    path <- dir(path, full.names=TRUE)
    install.packages2(path, repos=NULL, type="source")
  }
  main <- function() {
    if (exists("CONTEXT_ROOT")) {
      root <- get("CONTEXT_ROOT")
    } else {
      args <- commandArgs(TRUE)
      if (length(args) != 1L) {
        stop("Usage: context_bootstrap <root>")
      }
      root <- args[[1]]
    }
    bootstrap(root)
  }

  env <- environment(write_bootstrap)
  funs_context <- vcapply(find_funcs(bootstrap, env),
                          fun_to_str, env, USE.NAMES=FALSE)
  funs_bootstrap <- vcapply(c("bootstrap", "main"),
                            fun_to_str, environment(), USE.NAMES=FALSE)
  code <- c("#!/usr/bin/env Rscript",
            "# autogenerated by context; do not edit",
            "local({",
            funs_context,
            funs_bootstrap,
            "main()",
            "})")

  dir.create(root, FALSE, TRUE)
  writeLines(as.character(packageVersion(.packageName)), path_version(root))

  dest <- path_bootstrap(root)
  writeLines(code, dest)
  Sys.chmod(dest, "0755")
  invisible(dest)
}

write_runner <- function(path) {
  env <- environment(install_context)
  funs <- vcapply(c("main_parse_args", find_funcs(main_parse_args, env)),
                  fun_to_str, env, USE.NAMES=FALSE)

  ## This code is a bit horiffic because we need to get everything in
  ## place so that context will be found.  That requires getting just
  ## enough so that use_local_library is found, and parsing the
  ## arguments to get the correct version.  This makes a much less
  ## robust runner than usual.  So at the same time we'll arrange to
  ## read the bootstrap script, too!
  code <- c("#!/usr/bin/env Rscript",
            "# autogenerated by context; do not edit",
            "library(methods)",
            'message("args:")',
            'message(paste(commandArgs(), collapse=", "))',
            "local({",
            funs,
            "args <- main_parse_args(commandArgs(TRUE))",
            "CONTEXT_ROOT <- args$root",
            'source(file.path(CONTEXT_ROOT, "context_bootstrap"), TRUE)',
            "})",
            "context:::main()")
  dest <- file.path(path, "context_runner")
  writeLines(code, dest)
  Sys.chmod(dest, "0755")
  invisible(dest)
}
